INSERT INTO player(username, password, skill_level, score, email, theme)
VALUES
('user1', 'password1', 2, 0, 'user1@example.com', 'dark'),
('user2', 'password2', 2, 3558, 'user2@example.com', 'light'),
('user3', 'password3', 3, 8694, 'user3@example.com', 'dark'),
('user4', 'password4', 1, 8733, 'user4@example.com', 'light'),
('user5', 'password5', 2, 1344, 'user5@example.com', 'dark'),
('user6', 'password6', 3, 2365, 'user6@example.com', 'light'),
('user7', 'password7', 1, 1627, 'user7@example.com', 'dark'),
('user8', 'password8', 2, 3335, 'user8@example.com', 'light'),
('user9', 'password9', 4, 7080, 'user9@example.com', 'dark'),
('user10', 'password10', 4, 569, 'user10@example.com', 'light');

INSERT INTO question(question, skill_level)
VALUES
('Hello!', 1),
('My name''s Ben.', 1),
('What''s your name (singular)?', 1),
('Where am I?', 1),
('Where can I get a drink (water)?', 2),
('Where are the nearest toilets?', 2),
('Thank you.', 1),
('Excuse me.', 1),
('How are you?', 1),
('I''m lost.', 1),
('Can you help me?', 1),
('Where is the nearest hospital?', 3),
('How much does this cost?', 2),
('I need a taxi.', 1),
('Where is the nearest ATM?', 3),
('Help!', 1),
('Goodbye!', 1),
('How are you doing?', 1),
('I don''t understand.', 1),
('What time is it?', 1),
('Where is the nearest restaurant?', 3),
('Can you speak slower?', 2),
('I''m hungry.', 1),
('I need help.', 1),
('How do I get to the airport?', 2),
('Please, wait a moment.', 2),
('I need a doctor.', 2),
('Can I use your phone, please?', 2),
('I am allergic to peanuts.', 2),
('The bill, please.', 1),
('Can I have the Wi-Fi password?', 3),
('Do you speak English?', 1),
('I would like a coffee.', 1),
('What is the weather like?', 1),
('I''m looking for the subway.', 2),
('Could you recommend a good restaurant?', 3),
('How far is the city center?', 4),
('I would like to book a room.', 3);

INSERT INTO answer (question_id, answer, is_correct)
VALUES
(1, '¡Hola!', TRUE),
(2, 'Mi nombre es Ben.', TRUE),
(3, '¿Cómo se llama?', TRUE),
(4, '¿Dónde estoy?', TRUE),
(5, '¿Dónde puedo conseguir una bebida?', TRUE),
(6, '¿Dónde están los baños más cercanos?', TRUE),
(7, 'Gracias.', TRUE),
(8, 'Disculpe.', TRUE),
(9, '¿Cómo estás?', TRUE),
(10, 'Estoy perdido/a.', TRUE),
(11, '¿Me puedes ayudar?', TRUE),
(12, '¿Dónde está el hospital más cercano?', TRUE),
(13, '¿Cuánto cuesta esto?', TRUE),
(14, 'Necesito un taxi.', TRUE),
(15, '¿Dónde está el cajero automático más cercano?', TRUE),
(16, '¡Ayuda!', TRUE),
(17, '¡Adiós!', TRUE),
(18, '¿Cómo estás?', TRUE),
(19, 'No entiendo.', TRUE),
(20, '¿Qué hora es?', TRUE),
(21, '¿Dónde está el restaurante más cercano?', TRUE),
(22, '¿Puedes hablar más despacio?', TRUE),
(23, 'Tengo hambre.', TRUE),
(24, 'Necesito ayuda.', TRUE),
(25, '¿Cómo llego al aeropuerto?', TRUE),
(26, 'Por favor, espera un momento.', TRUE),
(27, 'Necesito un(a) doctor(a/o)', TRUE),
(28, '¿Puedo usar su teléfono?', TRUE),
(29, 'Soy alérgic(o/a) a los cacahuetes', TRUE),
(30, 'La cuenta, por favor.', TRUE),
(31, '¿Puedo tener la contraseña de Wi-Fi?', TRUE),
(32, '¿Hablas inglés?', TRUE),
(33, 'Me gustaría un café.', TRUE),
(34, '¿Cómo está el clima?', TRUE),
(35, 'Estoy buscando el metro.', TRUE),
(36, '¿Podrías recomendar un buen restaurante?', TRUE),
(37, '¿Qué tan lejos está el centro de la ciudad?', TRUE),
(38, 'Me gustaría reservar una habitación.', TRUE),
(1, '¡Hela!', FALSE),
(2, 'Mi amigo es Ben.', FALSE),
(3, '¿Cómo se llaman?', FALSE),
(4, '¿Dónde vas?', FALSE),
(5, '¿Dónde puedo comprar una comida?', FALSE),
(6, '¿Dónde están las cercanos más toiletas?', FALSE),
(7, 'García.', FALSE),
(8, 'Disclupi.', FALSE),
(9, '¿Cómo eres?', FALSE),
(10, 'Estoy cansado/a.', FALSE),
(11, '¿Me puedes bailar?', FALSE),
(12, '¿Dónde está la tienda más cercana?', FALSE),
(13, '¿Cuánto tiempo hace esto?', FALSE),
(14, 'Necesito una taxa.', FALSE),
(15, '¿Dónde está el cine más cercano?', FALSE),
(16, '¡Agua!', FALSE),
(17, '¡Abiós!', FALSE),
(18, '¿Cómo te sientes?', FALSE),
(19, 'No hablo español.', FALSE),
(20, '¿Qué clima es?', FALSE),
(21, '¿Dónde está el banco más cercano?', FALSE),
(22, '¿Puedes cantar más alto?', FALSE),
(23, 'Tengo frío.', FALSE),
(24, 'Necesito comida.', FALSE),
(25, '¿Cómo llego al airporto?', FALSE),
(26, 'Por favor, cierra la puerta.', FALSE),
(27, 'Necesito un(a) medicin(a/o)', FALSE),
(28, '¿Puedo usar su telé?', FALSE),
(29, 'Soy allérgic(o/a) a los cahacuetes', FALSE),
(30, 'La billa, por favor.', FALSE),
(31, '¿Puedo tener la pantraseña de Wi-Fi?', FALSE),
(32, '¿Hablas inglé?', FALSE),
(33, 'Me gustaría una café.', FALSE),
(34, '¿Cómo es el clima?', FALSE),
(35, 'Estoy buscando la metro.', FALSE),
(36, '¿Podrías recomendar un buen restorán?', FALSE),
(37, '¿Cuánto dista el centro de la ciudad?', FALSE),
(38, 'Me gustaría reservar un cuarto.', FALSE),
(1, '¡Hola!', FALSE),
(2, 'Mi comida es Ben.', FALSE),
(3, '¿Cóma te llama?', FALSE),
(4, '¿Dónda soy?', FALSE),
(5, '¿Dónde puedo ver una película?', FALSE),
(6, '¿Dónde estos los toiletas más cercanos?', FALSE),
(7, 'Gracios.', FALSE),
(8, 'Distrúyeme.', FALSE),
(9, '¿Cóme stás?', FALSE),
(10, 'Estoy feliz.', FALSE),
(11, '¿Me puedes llamar?', FALSE),
(12, '¿Dónde está la licarnas más cercana?', FALSE),
(13, '¿Cuánto come esto?', FALSE),
(14, 'Necesito una carrita.', FALSE),
(15, '¿Dónde está el dinera machina más cercano?', FALSE),
(16, '¡Ayedo!', FALSE),
(17, '¡Adió!', FALSE),
(18, '¿Cómo te llamas?', FALSE),
(19, 'No estoy entendiendo.', FALSE),
(20, '¿Qué día es?', FALSE),
(21, '¿Dónde está el parque más cercano?', FALSE),
(22, '¿Puedes caminar más rápido?', FALSE),
(23, 'Tengo sueño.', FALSE),
(24, 'Necesito agua.', FALSE),
(25, '¿Cómo llego al planerado?', FALSE),
(26, 'Por favor, ven conmigo.', FALSE),
(27, 'Neceisto un(a) enferm(a/o)', FALSE),
(28, '¿Puedo usar su fono?', FALSE),
(29, 'Soy alérgic(o/a) a los cacahuetes', FALSE),
(30, 'La telerida, por favor', FALSE),
(31, '¿Puedo tener la communareña de Wi-Fi?', FALSE),
(32, '¿Hablas ingliso?', FALSE),
(33, 'Me gustaría un caféa.', FALSE),
(34, '¿Cómo está la clima?', FALSE),
(35, 'Estoy buscando el autobús.', FALSE),
(36, '¿Podrías recomendar un restaurante bueno?', FALSE),
(37, '¿Cuánto es el centro de la ciudad?', FALSE),
(38, 'Me gustaría reservar una cuarta.', FALSE),
(1, '¡Hallo!', FALSE),
(2, 'Mi casa es Ben.', FALSE),
(3, '¿Cómo se amas?', FALSE),
(4, '¿Dónde vamos?', FALSE),
(5, '¿Dónde puedo conseguir un bebido?', FALSE),
(6, '¿Dónde están los cercanos?', FALSE),
(7, 'Grande.', FALSE),
(8, 'Discolpi.', FALSE),
(9, '¿Cómo vives?', FALSE),
(10, 'Estoy ocupado/a.', FALSE),
(11, '¿Me puedes comerme?', FALSE),
(12, '¿Dónde está el hopistalos más cercano?', FALSE),
(13, '¿Cuánto beso esto?', FALSE),
(14, 'Necesito una carrita.', FALSE),
(15, '¿Dónde está el automático dinero más cercano?', FALSE),
(16, '¡Amor!', FALSE),
(17, '¡Adias!', FALSE),
(18, '¿Cómo comes?', FALSE),
(19, 'No estoy cansado.', FALSE),
(20, '¿Qué año es?', FALSE),
(21, '¿Dónde está el cine más cercano?', FALSE),
(22, '¿Puedes comer más despacio?', FALSE),
(23, 'Tengo miedo.', FALSE),
(24, 'Necesito música.', FALSE),
(25, '¿Cómo llego al aviato?', FALSE),
(26, 'Por favor, dame un regalo.', FALSE),
(27, 'Necesito un(a) farmaci(a/o)', FALSE),
(28, '¿Puedo usar su computérita?', FALSE),
(29, 'Soy allérgic(o/a) a los cacahuetes', FALSE),
(30, 'La billa, por favor.', FALSE),
(31, '¿Puedo tener la pastereña de Wi-Fi?', FALSE),
(32, '¿Hablas ingleses?', FALSE),
(33, 'Me gustaría un caféa.', FALSE),
(34, '¿Cómo es el tiempo?', FALSE),
(35, 'Estoy buscando el tren.', FALSE),
(36, '¿Podrías recomendar un buen restorán?', FALSE),
(37, '¿Cuánto es el centro de la ciudad?', FALSE),
(38, 'Me gustaría reservar un habitación.', FALSE);